### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [4binzzzz/PY202309#1]
### 없는 파일
- project/week8/search_engine.ipynb
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 없는 PDF 파일
- project/week8/search_engine.pdf
	 - 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week3/list_and_tuple
    - invalid syntax. Perhaps you forgot a comma? (<unknown>, line 58)
        - menu = (Americano, Caffe Latte, Caffe Mocha, Iced Tea) #튜플 생성
        - 위 코드가 문자열로 작성되지 않아서 변수 취급되고 있습니다.
        - 변수 이름으로도 공백이 포함되어 제대로된 코드 실행이 되지 않습니다.
        - 문자열로 변경해주세요.

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in practice/week5/turtle

**Comment by 4binzzzz** [comment]
이슈 해결했습니다. 

[isssue-1] update files prior to midterm
-없는 파일 수정 : project/week8/search_engine.ipynb
-없는 PDF파일 수정 : project/week8/search_engine.pdf
-에러 : challenge/week3/list_and_tuple
